G1/urls.py
"""
File location: ...G1/urls.py
Description: This file contains the URL patterns for the G1 app.
Author: Rachit Khare
(c) 2024 RDM4Lab - all rights reserved
"""

# Django imports
from django.urls import path

# Application imports
from G1 import views

app_name = "G1"

# ------------------------------------------
# URL patterns for the G1 app
# ------------------------------------------

urlpatterns = [
    path(
        "",
        views.G1_data,
        name="G1-data",
    ),
    path(
        "add/",
        views.G1_data_add,
        name="G1-data-add",
    ),
    path(
        "<int:pk>/edit/",
        views.G1_data_edit,
        name="G1-data-edit",
    ),
    path(
        "<int:pk>/toggle_active/",
        views.G1_toggle_active,
        name="G1-toggle-active",
    ),
    path(
        "analysis/",
        views.G1_data_analysis,
        name="G1-data-analysis",
    ),
]

G3/urls.py
"""
File location: ...G3/urls.py
Description: This file contains the URL patterns for the G3 app.
Author: Rachit Khare
(c) 2024 RDM4Lab - all rights reserved
"""

# Django imports
from django.urls import path

# Application imports
from G3 import views

app_name = "G3"

# ------------------------------------------
# URL patterns for the G3 app
# ------------------------------------------

urlpatterns = [
    path(
        "",
        views.G3_data,
        name="G3-data",
    ),
    path(
        "<int:pk>/toggle_active/",
        views.G3_toggle_active,
        name="G3-toggle-active",
    ),
    path(
        "add/",
        views.G3_data_add,
        name="G3-data-add",
    ),
    path(
        "<int:pk>/edit/",
        views.G3_data_edit,
        name="G3-data-edit",
    ),
    path(
        "analysis/",
        views.G3_data_analysis,
        name="G3-data-analysis",
    ),
    path(
        "simulation/",
        views.G3_data_simulation,
        name="G3-data-simulation",
    ),
]

rdm4lab/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.apps import apps

urlpatterns = [
    path("admin/", admin.site.urls),  # Admin site
    path("", include("main.urls")),  # Main app
    path("", include("django.contrib.auth.urls")),  # Authentication
    path("ckeditor/", include("ckeditor_uploader.urls")),  # CKEditor file uploader
]

# Include the URLs of the apps that are installed
EXPERIMENTS_APPS = ["G1", "G3"]
for app_name in EXPERIMENTS_APPS:
    # Check if the app with the given name is installed
    if apps.is_installed(app_name):
        # Include the URLs of the app with a unique namespace
        urlpatterns += [
            path(
                f"my-experiments/{app_name}/data~/",
                include(f"{app_name}.urls", namespace=app_name),
            )
        ]
    else:
        pass

# Add media files to urlpatterns only if DEBUG is True i.e. during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

G3/forms.py
"""
File location: ...G3/forms.py
Description: This file contains the forms for the G3 app.
Author: Rachit Khare
(c) 2024 RDM4Lab - all rights reserved
"""

# Django imports
from django import forms

# Application imports
from G3.models import G3Data, G3Metadata
from G3.validators import valid_file_extensions

# Third-party imports
from crispy_forms.helper import FormHelper


# ------------------------------------------
# Forms for the G3 app
# ------------------------------------------


class G3DataForm(forms.ModelForm):
    """
    This form is used to upload the data for the experiment.
    """

    file = forms.FileField(
        label="Raw Data",
        required=False,
        widget=forms.FileInput(
            attrs={
                "accept": ",".join(valid_file_extensions),
            }
        ),
        help_text=f"Upload the raw date file for this experiment.",
    )

    class Meta:
        model = G3Data
        fields = ["id", "file"]

    def __init__(self, *args, **kwargs):
        id = kwargs.pop("id", None)
        super(G3DataForm, self).__init__(*args, **kwargs)

        # Temporarily remove the file_field from the form
        file_field = self.fields.pop("file")
        # Add the metadata fields to the form
        self.add_metadata_fields()
        # Re-add the file_field at the end
        self.fields["file"] = file_field
        # Set the initial value of the id field and disable it
        self.fields["id"].initial = id
        self.fields["id"].disabled = True

    def add_metadata_fields(self):
        """
        Method to add the metadata fields to the form.
        """

        metadata = G3Metadata.objects.first()
        if not metadata:
            return

        # Sort the metadata fields based on the order
        metadata_fields = metadata.fields
        sorted_metadata_fields = dict(
            sorted(metadata_fields.items(), key=lambda item: item[1]["order"])
        )

        # Add metadata fields to the form
        for field, attrs in sorted_metadata_fields.items():
            label = (
                f"{attrs['label']} [in {attrs['unit']}]"
                if attrs["unit"]
                else attrs["label"]
            )

            if attrs["type"] == "float":
                self.fields[field] = forms.FloatField(
                    label=label,
                    required=attrs["required"],
                    help_text=attrs["description"],
                )


class G3SimulForm(forms.Form):
    """
    This form is used to input the parameters for the simulation.
    """

    def __init__(self, *args, **kwargs):
        super(G3SimulForm, self).__init__(*args, **kwargs)
        # Add the metadata fields to the form
        from G3.models import G3Metadata

        metadata = G3Metadata.objects.first()
        if not metadata:
            return

        # Sort the metadata fields based on the order
        metadata_fields = metadata.fields
        sorted_metadata_fields = dict(
            sorted(metadata_fields.items(), key=lambda item: item[1]["order"])
        )

        # Add the input and output fields to the form
        self.add_input_fields(sorted_metadata_fields)
        self.add_output_fields(sorted_metadata_fields)

    def add_input_fields(self, metadata_fields):
        """
        Method to add the input fields to the form.
        """

        # Add the input fields to the form.
        for field, attrs in metadata_fields.items():
            if attrs["scope"] == "input":
                label = (
                    f"{attrs['label']} [in {attrs['unit']}]"
                    if attrs["unit"]
                    else attrs["label"]
                )
                if attrs["type"] == "float":
                    self.fields[field] = forms.FloatField(
                        label=label,
                        required=attrs["required"],
                        help_text=attrs["description"],
                    )

    def add_output_fields(self, metadata_fields):
        """
        Method to add the output fields to the form.
        """

        # Add output fields to the form
        for field, attrs in metadata_fields.items():
            if attrs["scope"] == "result":
                label = (
                    f"{attrs['label']} [in {attrs['unit']}]"
                    if attrs["unit"]
                    else attrs["label"]
                )
                if attrs["type"] == "float":
                    self.fields[field] = forms.FloatField(
                        label=label,
                        required=False,
                        help_text=attrs["description"],
                    )
                self.fields[field].widget.attrs["readonly"] = True

G3/views.py
"""
File location: .../G3/views.py
Description: This file contains the views for the G3 app.
Author: Rachit Khare
(c) 2024 RDM4Lab - all rights reserved
"""

# Global imports
from main import ureg, Q_

# Django imports
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.db.models import Max
from django.http import HttpRequest, HttpResponse

# Application imports
from main.models import Experiment, UserExperiment
from G3.models import G3Data, G3Metadata, G3Results
from G3.forms import G3DataForm, G3SimulForm
from G3.simulations import perform_simulation
from G3.utils import (
    prepare_for_db_storage,
    prepare_for_html_display,
    convert_to_html_format,
)

# Third-party imports
import json
import plotly.utils

# ------------------------------------------
# Views for G3 experiment
# ------------------------------------------


@login_required(login_url="/login")
def G3_data(request):
    """
    This view is used to display the data for G3 experiment.
    """

    # Get the existing data into a queryset
    currentuser = request.user
    experiment = Experiment.objects.get(id="G3")
    userexperiment = UserExperiment.objects.get(
        student_id=currentuser.uid,
        experiment_id=experiment.uid,
    )
    queryset = G3Data.objects.filter(userexperiment_id=userexperiment.uid)

    # Get the metadata fields from G3Metadata and sort them
    metadata_fields = G3Metadata.objects.first().fields
    sorted_metadata_fields = dict(
        sorted(metadata_fields.items(), key=lambda item: item[1]["order"])
    )

    # Create a dictionary list to display the existing data points
    dataset = (
        [
            {
                "id": item.id,
                "raw_data": prepare_for_html_display(
                    data_dict=item.raw_data,
                    metadata_fields=sorted_metadata_fields,
                ),
                "file": item.file.url if item.file else None,
                "is_active": item.is_active,
                "is_simulated": item.is_simulated,
            }
            for item in queryset
        ]
        if queryset
        else None
    )

    context = {"dataset": dataset}

    return render(request, "G3/G3-data.html", context)


@login_required(login_url="/login")
def G3_data_add(request):
    """
    This view allows the user to add new data for G3 experiment.
    """

    # Get the existing data into a queryset
    currentuser = request.user
    experiment = Experiment.objects.get(id="G3")
    userexperiment = UserExperiment.objects.get(
        student_id=currentuser.uid,
        experiment_id=experiment.uid,
    )
    queryset = G3Data.objects.filter(userexperiment_id=userexperiment.uid)

    # Get the max ID value of the dataset
    max_id = 0 if not queryset else queryset.aggregate(Max("id"))["id__max"]
    next_id = max_id + 1

    # Get the metadata fields from G3Metadata and sort them
    metadata_fields = G3Metadata.objects.first().fields
    sorted_metadata_fields = dict(
        sorted(metadata_fields.items(), key=lambda item: item[1]["order"])
    )

    if request.method == "POST":
        form = G3DataForm(request.POST, request.FILES, id=next_id)
        # Check if the form is valid
        if form.is_valid():
            # If the form is valid, process data for storage
            form_data = form.cleaned_data
            # Prepare the data for database storage
            metadata = prepare_for_db_storage(
                data_dict=form_data,
                metadata_fields=sorted_metadata_fields,
            )
            metadata["id"] = next_id
            metadata["is_active"] = True
            metadata["is_simulated"] = False
            # Create a new G3Data instance and save it to the database
            g3_data = G3Data(
                id=next_id,
                is_active=True,
                is_simulated=False,
                raw_data=metadata,
                file=form_data["file"],
                userexperiment=userexperiment,
            )
            g3_data.save()

            return redirect("G3:G3-data")
    else:
        form = G3DataForm(id=next_id)

    return render(request, "G3/G3-data-add.html", {"form": form})


@login_required(login_url="/login")
def G3_data_edit(request, pk):
    """
    This view allows the user to edit existing data point for the G3 experiment.
    """

    # Get the existing data point with the given ID
    g3_data = G3Data.objects.get(id=pk)
    # Get the metadata fields from G3Metadata and sort them
    metadata_fields = G3Metadata.objects.first().fields
    sorted_metadata_fields = dict(
        sorted(metadata_fields.items(), key=lambda item: item[1]["order"])
    )

    # prepare initial data for the form
    initial_data = prepare_form_data(g3_data.raw_data)

    if request.method == "POST":
        form = G3DataForm(
            request.POST,
            request.FILES,
            instance=g3_data,
            initial=initial_data,
        )
        if form.is_valid():
            form_data = form.cleaned_data
            # Prepare the data for database storage
            metadata = prepare_for_db_storage(
                data_dict=form_data,
                metadata_fields=sorted_metadata_fields,
            )
            metadata["id"] = pk
            metadata["is_active"] = g3_data.is_active
            metadata["is_simulated"] = g3_data.is_simulated
            # Update the existing G3Data instance and save it to the database
            g3_data.raw_data = metadata
            g3_data.file = form_data["file"]
            g3_data.save(update_fields=["raw_data", "file"])

            return redirect("G3:G3-data")
    else:
        form = G3DataForm(
            id=pk,
            initial=initial_data,
        )

    return render(
        request,
        "G3/G3-data-edit.html",
        {
            "id": pk,
            "form": form,
        },
    )


@login_required(login_url="/login")
def G3_data_analysis(request):
    """
    This view is used to display the analyzed data for the G3 experiment.
    """

    # Get the existing data points into a queryset
    currentuser = request.user
    experiment = Experiment.objects.get(id="G3")
    userexperiment = UserExperiment.objects.get(
        student_id=currentuser.uid,
        experiment_id=experiment.uid,
    )
    queryset = G3Data.objects.filter(userexperiment_id=userexperiment.uid)

    # ------------------------------------------
    # Prepare the processed dataset for display
    # ------------------------------------------

    proc_dataset = []
    for item in queryset:
        data = {
            "id": item.id,
            "is_active": item.raw_data.get("is_active"),
            "is_simulated": item.raw_data.get("is_simulated"),
        }

        metadata = {
            "T_reactor": Q_(item.raw_data["T_reactor"]).to("degC"),
            "p": Q_(item.proc_data["p"]).to("bar"),
            "tau": Q_(item.proc_data["tau"]).to("g*h/mol").to_base_units(),
            "conversion": Q_(item.proc_data["conversion"]).to("percent"),
        }

        html_metadata = convert_to_html_format(data_dict=metadata)
        data.update({"proc_data": html_metadata})
        proc_dataset.append(data)

    # ------------------------------------------
    # Prepare the rate dataset for display
    # ------------------------------------------

    g3results = G3Results.objects.get(userexperiment=userexperiment)
    rate_dicts = g3results.rate_dicts

    rate_dataset = []
    for d in rate_dicts:
        if d.get("rate") is not None:
            # If the rate is not None, then prepare the data for display
            metadata = {
                "p": Q_(d.get("p")).to("bar"),
                "T_reactor": Q_(d.get("T_reactor")).to("degC"),
                "rate": Q_(d.get("rate")).to("mol/(g*h)"),
                "r_squared": Q_(d.get("r_squared")).to("unitless"),
            }
            html_metadata = convert_to_html_format(data_dict=metadata)
            plotdata = d.get("plotdata")
            fitdata = d.get("fitdata")
            simuldata = d.get("simuldata")
            # Get the ref_ids and is_simulated and sort them
            ref_ids = d.get("ref_ids")
            is_simulated = d.get("is_simulated")
            combined = list(zip(ref_ids, is_simulated))
            combined.sort()
            ref_ids, is_simulated = zip(*combined)
            # Append the data to the dataset
            rate_dataset.append(
                {
                    "id": d.get("id"),
                    "ref_ids": ref_ids,
                    "metadata": html_metadata,
                    "is_simulated": is_simulated,
                    "plots": json.dumps(
                        [plotdata, simuldata, fitdata],
                        cls=plotly.utils.PlotlyJSONEncoder,
                    ),
                    "error": d.get("error"),
                }
            )

    # ------------------------------------------
    # Prepare the dataset for Ea analysis
    # ------------------------------------------

    ea_dicts = g3results.ea_dicts

    ea_dataset = []
    for d in ea_dicts:
        if d.get("Ea") is not None:
            # If the Ea is not None, then prepare the data for display
            metadata = {
                "p": Q_(d.get("p")).to("bar"),
                "Ea": Q_(d.get("Ea")).to("kJ/mol"),
                "r_squared": Q_(d.get("r_squared")).to("unitless"),
            }
            html_metadata = convert_to_html_format(data_dict=metadata)
            plotdata = d.get("plotdata")
            fitdata = d.get("fitdata")
            # Get the ref_ids and sort them
            ref_ids = d.get("ref_ids")
            ref_ids.sort()
            # Append the data to the dataset
            ea_dataset.append(
                {
                    "id": d.get("id"),
                    "ref_ids": ref_ids,
                    "metadata": html_metadata,

G3/templates/G3/G3-data-add.html
{% extends 'base.html' %}

{% comment %}
File location: ...G3/G3-data-add.html
Description: This template is used to add a new data point for this experiment.
Author: Rachit Khare
(c) 2024, RDM4Lab - all rights reserved
{% endcomment %}

{% block title %}
RDM4Lab | G3 | Add Data
{% endblock %}

{% block content_title %}
Add Data
{% endblock %}

{% block content_description %}
<p>Here you can add a new data point for this experiment.</p>
<p><a href="{% url 'G3:G3-data' %}">Click here</a> to go back to the 
    data management page.</p>
<hr>
{# load custom tags and static files #}
{% load crispy_forms_tags %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'G3/css/G3.css' %}">
{% endblock %}

{% block content %}
<!-- Form to add data -->
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="d-grid gap-2 col-6 mx-auto">
        <button class="btn btn btn-outline-primary btn-block" type="submit">Add Data</button>
    </div>
</form>
{% endblock %}

{% block breadcrumbs %}
<li class="breadcrumb-item">
    <a href="{% url 'my-experiments' %}">
        <span>My Experiments</span>
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'my-experiments-id' 'G3' %}">
        <span>G3</span>
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'G3:G3-data' %}">
        <span>Data Management</span>
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'G3:G3-data-add' %}">
        <span>Add Data</span>
    </a>
</li>
{% endblock %}

G3/templates/G3/G3-data-edit.html
{% extends 'base.html' %}

{% comment %}
File location: ...G3/G3-data-add.html
Description: This template is used to add a new data point for this experiment.
Author: Rachit Khare
(c) 2024, RDM4Lab - all rights reserved
{% endcomment %}

{% block title %}
RDM4Lab | G3 | Edit Data
{% endblock %}

{% block content_title %}
Edit Data
{% endblock %}

{% block content_description %}
<p>Here you can edit an existing data point for this experiment.</p>
<p><a href="{% url 'G3:G3-data' %}">Click here</a> to go back to the 
    data management page.</p>
<hr>
{# load custom tags and static files #}
{% load crispy_forms_tags %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'G3/css/G3.css' %}">
{% endblock %}

{% block content %}
<!-- Form to add data -->
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="d-grid gap-2 col-6 mx-auto">
        <button class="btn btn btn-outline-primary btn-block" type="submit">Update Data</button>
    </div>
</form>
{% endblock %}

{% block breadcrumbs %}
<li class="breadcrumb-item">
    <a href="{% url 'my-experiments' %}">
        <span>My Experiments</span>
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'my-experiments-id' 'G3' %}">
        <span>G3</span>
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'G3:G3-data' %}">
        <span>Data Management</span>
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'G3:G3-data-edit' id %}">
        <span>Edit Data Point # {{ id }}</span>
    </a>
</li>
{% endblock %}

G3/templates/G3/G3-data-simulation.html
{% extends 'base.html' %}

{% comment %}
File location: ...G3/G3-data-simulation.html
Description: This template is used to simulate additional data for experiment G3.
Author: Rachit Khare
(c) 2024, RDM4Lab - all rights reserved
{% endcomment %}

{% block title %}
RDM4Lab | G3 | Simulation
{% endblock %}

{% block content_title %}
Simulation
{% endblock %}

{% block content_description %}
<p>Here you can simulate additional data for experiment G3.</p>
<p><a href="{% url 'G3:G3-data' %}">Click here</a> to 
    go back to data management page for your data.</p>
<hr>
{# load custom tags and static files #}
{% load crispy_forms_tags %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'G3/css/G3.css' %}">
{% load crispy_forms_tags %}
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="d-grid gap-2 col-6 mx-auto">
        <button class="btn btn-outline-primary btn-block" type="submit" name="action" value="simulate">Simulate</button>
        <button class="btn btn-outline-primary btn-block" type="submit" name="action" value="add-data">Add Data</button>
    </div>
</form>
{% endblock %}

{% block breadcrumbs %}
<!-- link to my-experiments page -->
<li class="breadcrumb-item">
    <a href="{% url 'my-experiments' %}">
        <span>My Experiments</span>
    </a>
</li>
<!-- link to Experiment main page -->
<li class="breadcrumb-item">
    <a href="{% url 'my-experiments-id' 'G3' %}">
        <span>G3</span>
    </a>
</li>
<!-- link to this page -->
<li class="breadcrumb-item">
    <a href="{% url 'G3:G3-data' %}">
        <span>Data Management</span>
    </a>
</li>
<!-- link to this page -->
<li class="breadcrumb-item">
    <a href="{% url 'G3:G3-data-simulation' %}">
        <span>Simulation</span>
    </a>
</li>
{% endblock %}

G3/templates/G3/G3-data.html
{% extends 'base.html' %}

{% comment %}
File location: ...G3/G3-data.html
Description: This template is used to display the data for this experiment.
Author: Rachit Khare
(c) 2024, RDM4Lab - all rights reserved
{% endcomment %}

{% block title %}
RDM4Lab | G3 | Data
{% endblock %}

{% block content_title %}
Data Management
{% endblock %}

{% block content_description %}
<p>Here you can manage the data for this experiment.</p>
<p><a href="{% url 'G3:G3-data-analysis' %}">Click here</a> to 
    access automated data analysis for your data.</p>
<hr>
{# load custom tags and static files #}
{% load custom_tags %}
{% load humanize %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'G3/css/G3.css' %}">
{% endblock %}

{% block content %}
<!-- Table to display data -->
{% if dataset is None %}
<div class="alert alert-danger" role="alert">
    No data available for this experiment.
</div>
{% else %}
<div class="table-container card card-body">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                {% with labels=dataset|get_at_index:0|dict_key:"raw_data" %}
                {% for label in labels %}
                <th>{{ label }}</th>
                {% endfor %}
                {% endwith %}
                <th>File</th>
                <th>Enable/Disable</th>
            </tr>
        </thead>
        <tbody>
            {% for datapoint in dataset %}
            <tr>
                <td>
                    {% if datapoint|dict_key:"is_simulated" %}
                    <mark>
                    {% endif %}
                    <a href="{% url 'G3:G3-data-edit' datapoint|dict_key:"id" %}">
                    {{ datapoint|dict_key:"id" }}</a>
                    {% if datapoint|dict_key:"is_simulated" %}
                    </mark>
                    {% endif %}
                </td>
                {% with labels=datapoint|dict_key:"raw_data" %}
                {% for item in labels %}
                <td>{{ labels|dict_key:item|intcomma }}</td>
                {% endfor %}
                {% if datapoint|dict_key:"file" %}
                <td><a href="{{ datapoint|dict_key:"file" }}">Download File</a></td>
                {% else %}
                <td>No file</td>
                {% endif %}
                <td>
                    <a href={% url 'G3:G3-toggle-active' datapoint|dict_key:"id" %}>
                    {% if datapoint|dict_key:"is_active" %}
                    <span class="badge bg-success">Enabled</span>
                    {% else %}
                    <span class="badge bg-danger">Disabled</span>
                    {% endif %}
                    </a>
                </td>
                {% endwith %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <p><mark>Simulated</mark> data point</p>
</div>
{% endif %}
<div class="text-center pt-1">
    <a class="btn btn-outline-primary" href="{% url 'G3:G3-data-add' %}">Add Data</a>
</div>
<hr>
<div>
    <a href="{% url 'G3:G3-data-simulation' %}">Click here</a> to 
    simulate additional data for this exepriment.
</div>
{% endblock %}

{% block breadcrumbs %}
<li class="breadcrumb-item">
    <a href="{% url 'my-experiments' %}">
        <span>My Experiments</span>
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'my-experiments-id' 'G3' %}">
        <span>G3</span>
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'G3:G3-data' %}">
        <span>Data Management</span>
    </a>
</li>
{% endblock %}