G1/urls.py
"""
File location: ...G1/urls.py
Description: This file contains the URL patterns for the G1 app.
Author: Rachit Khare
(c) 2024 RDM4Lab - all rights reserved
"""

# Django imports
from django.urls import path

# Application imports
from G1 import views

app_name = "G1"

# ------------------------------------------
# URL patterns for the G1 app
# ------------------------------------------

urlpatterns = [
    path(
        "",
        views.G1_data,
        name="G1-data",
    ),
    path(
        "add/",
        views.G1_data_add,
        name="G1-data-add",
    ),
    path(
        "<int:pk>/edit/",
        views.G1_data_edit,
        name="G1-data-edit",
    ),
    path(
        "<int:pk>/toggle_active/",
        views.G1_toggle_active,
        name="G1-toggle-active",
    ),
    path(
        "analysis/",
        views.G1_data_analysis,
        name="G1-data-analysis",
    ),
]

rdm4lab/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.apps import apps

urlpatterns = [
    path("admin/", admin.site.urls),  # Admin site
    path("", include("main.urls")),  # Main app
    path("", include("django.contrib.auth.urls")),  # Authentication
    path("ckeditor/", include("ckeditor_uploader.urls")),  # CKEditor file uploader
]

# Include the URLs of the apps that are installed
EXPERIMENTS_APPS = ["G1", "G3"]
for app_name in EXPERIMENTS_APPS:
    # Check if the app with the given name is installed
    if apps.is_installed(app_name):
        # Include the URLs of the app with a unique namespace
        urlpatterns += [
            path(
                f"my-experiments/{app_name}/data~/",
                include(f"{app_name}.urls", namespace=app_name),
            )
        ]
    else:
        pass

# Add media files to urlpatterns only if DEBUG is True i.e. during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

G1/forms.py
"""
File location: ...G1/forms.py
Description: This file contains the forms for the G1 app.
Author: Rachit Khare
(c) 2024 RDM4Lab - all rights reserved
"""

# Django imports
from django import forms
from django.utils.translation import gettext as _
from django.utils.safestring import mark_safe

# Application imports
from G1.models import G1Data, G1Metadata
from G1.validators import valid_file_extensions

# Third-party imports
import pandas as pd


class G1DataForm(forms.ModelForm):
    file = forms.FileField(
        label="Upload data file",
        required=True,
        widget=forms.FileInput(
            attrs={
                "accept": ",".join(valid_file_extensions),
            }
        ),
        help_text=_("Download the file template <a href='#'>here</a>."),
    )

    class Meta:
        model = G1Data
        fields = ["id", "file"]

    def __init__(self, *args, **kwargs):
        template_url = kwargs.pop("template_url", "#")
        id = kwargs.pop("id", None)
        super(G1DataForm, self).__init__(*args, **kwargs)

        # Temporarily remove the file field from the form
        file_field = self.fields.pop("file")
        # Add the metadata fields to the form
        self.add_metadata_fields()
        # Re-add the file field at the end
        self.fields["file"] = file_field
        # Add the help text to the file field with file download url
        self.fields["file"].help_text = mark_safe(
            _("Download the file template <a href='{url}'>here</a>.").format(
                url=template_url
            )
        )
        # Set the initial value of the id field and disable it
        self.fields["id"].initial = id
        self.fields["id"].disabled = True

    def add_metadata_fields(self):
        """
        Method to add the metadata fields to the form.
        """

        from G1.models import G1Metadata

        metadata = G1Metadata.objects.first()
        if not metadata:
            return

        # Sort the metadata fields based on the order
        metadata_fields = metadata.fields
        sorted_metadata_fields = dict(
            sorted(metadata_fields.items(), key=lambda item: item[1]["order"])
        )

        # Add metadata fields to the form
        for field, attrs in sorted_metadata_fields.items():
            label = (
                f"{attrs['label']} [in {attrs['unit']}]"
                if attrs["unit"]
                else attrs["label"]
            )

            if attrs["type"] == "float":
                self.fields[field] = forms.FloatField(
                    label=label,
                    required=attrs["required"],
                    help_text=attrs["description"],
                )

    def clean(self):
        cleaned_data = super().clean()
        # Get the metadata fields from the G1Metadata model
        try:
            template = G1Metadata.objects.first().template
        except:
            # If the template is not found, set it to None
            template = None

        if template is not None:
            # If the template is found, check if the uploaded file matches the template
            file = cleaned_data.get("file")
            # Read the uploaded file and the template file
            xlsfile = pd.ExcelFile(file)
            xlstemplate = pd.ExcelFile(template)

            # Check if the sheet names are the same.
            if set(xlsfile.sheet_names) != set(xlstemplate.sheet_names):
                raise forms.ValidationError(
                    _(
                        "Please upload the correct file type based on the template for this experiment. The sheet names do not match."
                    )
                )
            else:
                # For each sheet in the excel file - check if the columns are the same
                for sheet in xlsfile.sheet_names:
                    xlsdata = pd.read_excel(xlsfile, sheet_name=sheet, header=1)
                    xlstemplatedata = pd.read_excel(
                        xlstemplate, sheet_name=sheet, header=1
                    )
                    if set(xlsdata.columns) != set(xlstemplatedata.columns):
                        raise forms.ValidationError(
                            _(
                                "Please upload the correct file type based on the template for this experiment. The column names do not match."
                            )
                        )

G1/views.py
"""
File location: ...G1/views.py
Description: This file contains the views for the G1 experiment.
Author: Rachit Khare
(c) 2024 RDM4Lab - all rights reserved
"""

# Global imports
from main.constants import R
from main import ureg, Q_

# Django imports
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.db.models import Max
from django.http import HttpRequest, HttpResponse

# Application imports
from main.models import Experiment, UserExperiment
from G1.models import G1Data, G1Metadata, G1Results
from G1.forms import G1DataForm
from G1.utils import (
    prepare_for_html_display,
    prepare_for_db_storage,
    convert_to_html_format,
)

# Third-party imports
import json

# ------------------------------------------
# Views for G1 experiment
# ------------------------------------------


@login_required(login_url="/login")
def G1_data(request):
    """
    This view is used to display the data for the G1 experiment.
    It fetches the data from the G1Data model and displays it in a table.
    """

    # Get the current datapoints for the G1 experiment into a queryset
    currentuser = request.user
    experiment = Experiment.objects.get(id="G1")
    userexperiment = UserExperiment.objects.get(
        student_id=currentuser.uid,
        experiment_id=experiment.uid,
    )
    queryset = G1Data.objects.filter(userexperiment_id=userexperiment.uid)

    # Get the metadata fields from G3Metadata and sort them
    metadata_fields = G1Metadata.objects.first().fields
    sorted_metadata_fields = dict(
        sorted(metadata_fields.items(), key=lambda item: item[1]["order"])
    )

    dataset = (
        [
            {
                "id": item.id,
                "raw_data": prepare_for_html_display(
                    data_dict=item.raw_data,
                    metadata_fields=sorted_metadata_fields,
                ),
                "file": item.file.url or None,
                "is_active": item.is_active,
            }
            for item in queryset
        ]
        if queryset
        else None
    )

    context = {"dataset": dataset}

    return render(request, "G1/G1-data.html", context)


@login_required(login_url="/login")
def G1_data_add(request):
    """
    This view is used to add data for the G1 experiment.
    """

    # Get the existing data points for the G1 experiment into a queryset
    currentuser = request.user
    experiment = Experiment.objects.get(id="G1")
    userexperiment = UserExperiment.objects.get(
        student_id=currentuser.uid,
        experiment_id=experiment.uid,
    )
    queryset = G1Data.objects.filter(userexperiment_id=userexperiment.uid)

    # Check if the template file is present, if not set it to None
    if G1Metadata.objects.first() is None:
        template = None
    else:
        # Get the template file from the G1Metadata model
        template = G1Metadata.objects.first().template

    # Get the max ID value of the dataset
    max_id = 0 if not queryset else queryset.aggregate(Max("id"))["id__max"]
    next_id = max_id + 1

    # Get the metadata fields from G3Metadata and sort them
    metadata_fields = G1Metadata.objects.first().fields
    sorted_metadata_fields = dict(
        sorted(metadata_fields.items(), key=lambda item: item[1]["order"])
    )

    if request.method == "POST":
        form = G1DataForm(
            request.POST, request.FILES, template_url=template.url, id=next_id
        )
        # Check if the form is valid
        if form.is_valid():
            # If the form is valid, process form data for storage
            form_data = form.cleaned_data
            # Get the metadata fields from the G1Metadata model
            metadata = prepare_for_db_storage(
                data_dict=form_data,
                metadata_fields=sorted_metadata_fields,
            )
            metadata["id"] = next_id
            metadata["is_active"] = True
            # Create a new G1Data instance and save it to the database
            g1_data = G1Data(
                id=next_id,
                is_active=True,
                is_processed=False,
                raw_data=metadata,
                file=form_data["file"],
                userexperiment=userexperiment,
            )
            g1_data.save()

            return redirect("G1:G1-data")
    else:
        form = G1DataForm(template_url=template.url, id=next_id)

    return render(
        request,
        "G1/G1-data-add.html",
        {
            "template": template,
            "form": form,
        },
    )


@login_required(login_url="/login")
def G1_data_edit(request, pk):
    """
    This view allows the user to edit existing data point for the G1 experiment.
    """

    # Get the existing data point with the given ID
    g1_data = G1Data.objects.get(id=pk)
    # Get the metadata fields from G3Metadata and sort them
    metadata_fields = G1Metadata.objects.first().fields
    sorted_metadata_fields = dict(
        sorted(metadata_fields.items(), key=lambda item: item[1]["order"])
    )

    # prepare initial data for the form
    initial_data = prepare_form_data(g1_data.raw_data)

    if request.method == "POST":
        form = G1DataForm(
            request.POST,
            request.FILES,
            instance=g1_data,
            initial=initial_data,
        )
        if form.is_valid():
            form_data = form.cleaned_data
            # Prepare the data for database storage
            metadata = prepare_for_db_storage(
                data_dict=form_data,
                metadata_fields=sorted_metadata_fields,
            )
            metadata["id"] = pk
            metadata["is_active"] = g1_data.is_active
            # Update the existing G3Data instance and save it to the database
            g1_data.raw_data = metadata
            g1_data.is_processed = False
            g1_data.file = form_data["file"]
            g1_data.save(update_fields=["raw_data", "file"])

            return redirect("G1:G1-data")
    else:
        form = G1DataForm(
            id=pk,
            initial=initial_data,
        )

    return render(
        request,
        "G1/G1-data-edit.html",
        {
            "id": pk,
            "form": form,
        },
    )


@login_required(login_url="/login")
def G1_toggle_active(request: HttpRequest, pk: int) -> HttpResponse:
    """
    This view is used to toggle the active status of a data point.
    """

    # Get the data point with the given ID
    g1data = G1Data.objects.get(id=pk)
    # Toggle the active status of the data point
    g1data.is_active = not g1data.is_active
    g1data.is_processed = False
    raw_data = g1data.raw_data
    raw_data.update({"is_active": g1data.is_active})
    g1data.save()

    # Redirect to the same page from which the action was triggered
    return redirect(request.META.get("HTTP_REFERER", "G1:G1-data"))


@login_required(login_url="/login")
def G1_data_analysis(request):
    """
    This view is used to analyze the data for the G1 experiment.
    """

    # Get the current datapoints for the G1 experiment into a queryset
    currentuser = request.user
    experiment = Experiment.objects.get(id="G1")
    userexperiment = UserExperiment.objects.get(
        student_id=currentuser.uid,
        experiment_id=experiment.uid,
    )
    queryset = G1Data.objects.filter(userexperiment_id=userexperiment.uid)

    # ------------------------------------------
    # Prepare the processed dataset for display
    # ------------------------------------------

    rate_dataset = []
    for item in queryset:
        plotdata = item.proc_data.get("plotdata")
        fitdata = item.proc_data.get("fitdata")
        data = {
            "id": item.id,
            "is_active": item.raw_data.get("is_active"),
            "plots": json.dumps([plotdata, fitdata]),
        }

        metadata = {
            "T_reaction": Q_(item.raw_data["T_reaction"]).to("degC"),
            "C_base": Q_(item.raw_data["C_base"]).to("mM"),
            "C_ester": Q_(item.raw_data["C_ester"]).to("mM"),
            "rate": Q_(item.proc_data["rate"]).to("mol/(l*s)"),
            "r_squared": Q_(item.proc_data["r_squared"]).to("unitless"),
        }

        html_metadata = convert_to_html_format(data_dict=metadata)
        data.update({"metadata": html_metadata})
        rate_dataset.append(data)

    # ------------------------------------------
    # Prepare the Ea dataset for display
    # ------------------------------------------

    # Get the G1Results instance for the current user
    g1results = G1Results.objects.get(userexperiment_id=userexperiment.uid)
    ea_dicts = g1results.ea_dicts

    ea_dataset = []
    for d in ea_dicts:
        if d.get("Ea") is not None:
            # If the Ea is not None, then prepare the data for display
            metadata = {
                "C_base": Q_(d.get("C_base")).to("mM"),
                "C_ester": Q_(d.get("C_ester")).to("mM"),
                "Ea": Q_(d.get("Ea")).to("kJ/mol"),
                "r_squared": Q_(d.get("r_squared")).to("unitless"),
            }
            html_metadata = convert_to_html_format(data_dict=metadata)
            plotdata = d.get("plotdata")
            fitdata = d.get("fitdata")
            # Get the ref_ids and sort them
            ref_ids = d.get("ref_ids")
            ref_ids.sort()
            # Append the data to the dataset
            ea_dataset.append(
                {
                    "id": d.get("id"),
                    "ref_ids": ref_ids,
                    "metadata": html_metadata,
                    "plots": json.dumps([plotdata, fitdata]),
                    "error": d.get("error"),
                }
            )

    # ------------------------------------------
    # Prepare the RO base dataset for display
    # ------------------------------------------

    ro_base_dicts = g1results.ro_base_dicts

    ro_base_dataset = []
    for d in ro_base_dicts:

G1/templates/G1/G1-data-add.html
<!-- G1/templates/G1/my-experiments-data.html -->
{% extends 'base.html' %}

{% block title %}
RDM4Lab | G1 | Add Data
{% endblock %}

{% block content_title %}
Add Data
{% endblock %}

{% block content_description %}
<p>Here you can add a new data point for this experiment.</p>
<p><a href="{% url 'G1:G1-data' %}">Click here</a> to go back to the 
    data management page.</p>
<hr>
{# load custom tags and static files #}
{% load crispy_forms_tags %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'G1/css/G1.css' %}">
{% endblock %}

{% block content %}
<!-- Form to add data -->
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="d-grid gap-2 col-6 mx-auto">
        <button class="btn btn btn-outline-primary btn-block" type="submit">Add Data</button>
    </div>
</form>
{% endblock %}

{% block breadcrumbs %}
<li class="breadcrumb-item">
    <a href="{% url 'my-experiments' %}">
        <span>My Experiments</span>
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'my-experiments-id' 'G1' %}">
        <span>G1</span>
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'G1:G1-data' %}">
        <span>Data Management</span>
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'G1:G1-data-add' %}">
        <span>Add Data</span>
    </a>
</li>
{% endblock %}

G1/templates/G1/G1-data-edit.html
{% extends 'base.html' %}

{% comment %}
File location: ...G1/G1-data-add.html
Description: This template is used to add a new data point for this experiment.
Author: Rachit Khare
(c) 2024, RDM4Lab - all rights reserved
{% endcomment %}

{% block title %}
RDM4Lab | G1 | Edit Data
{% endblock %}

{% block content_title %}
Edit Data
{% endblock %}

{% block content_description %}
<p>Here you can edit an existing data point for this experiment.</p>
<p><a href="{% url 'G1:G1-data' %}">Click here</a> to go back to the 
    data management page.</p>
<hr>
{# load custom tags and static files #}
{% load crispy_forms_tags %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'G1/css/G1.css' %}">
{% endblock %}

{% block content %}
<!-- Form to add data -->
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="d-grid gap-2 col-6 mx-auto">
        <button class="btn btn btn-outline-primary btn-block" type="submit">Update Data</button>
    </div>
</form>
{% endblock %}

{% block breadcrumbs %}
<li class="breadcrumb-item">
    <a href="{% url 'my-experiments' %}">
        <span>My Experiments</span>
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'my-experiments-id' 'G1' %}">
        <span>G1</span>
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'G1:G1-data' %}">
        <span>Data Management</span>
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'G1:G1-data-edit' id %}">
        <span>Edit Data Point # {{ id }}</span>
    </a>
</li>
{% endblock %}

G1/templates/G1/G1-data.html
{% extends 'base.html' %}

{% comment %}
File location: ...G1/G1-data.html
Description: This template is used to display the data for G1 experiment.
Author: Rachit Khare
(c) 2024, RDM4Lab - all rights reserved
{% endcomment %}

{% block title %}
RDM4Lab | G1 | Data
{% endblock %}

{% block content_title %}
Data Management
{% endblock %}

{% block content_description %}
<p>Here you can manage the data for this experiment.</p>
<p><a href="{% url 'G1:G1-data-analysis' %}">Click here</a> to 
    access automated data analysis for your data.</p>
<hr>
{# load custom tags and static files #}
{% load custom_tags %}
{% load humanize %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'G1/css/G1.css' %}">
{% endblock %}

{% block content %}
<!-- Table to display data -->
{% if dataset is None %}
<div class="alert alert-danger" role="alert">
    No data available for this experiment.
</div>
{% else %}
<div class="table-container card card-body">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                {% with labels=dataset|get_at_index:0|dict_key:"raw_data" %}
                {% for label in labels %}
                <th>{{ label }}</th>
                {% endfor %}
                {% endwith %}
                <th>File</th>
                <th>Enable/Disable</th>
            </tr>
        </thead>
        <tbody>
            {% for datapoint in dataset %}
            <tr>
                <td>
                    <a href="{% url 'G1:G1-data-edit' datapoint|dict_key:"id" %}">
                    {{ datapoint|dict_key:"id" }}</a>
                </td>
                {% with labels=datapoint|dict_key:"raw_data" %}
                {% for item in labels %}
                <td>{{ labels|dict_key:item|intcomma }}</td>
                {% endfor %}
                {% if datapoint|dict_key:"file" %}
                <td><a href="{{ datapoint|dict_key:"file" }}">Download File</a></td>
                {% else %}
                <td>No file</td>
                {% endif %}
                <td>
                    <a href={% url 'G1:G1-toggle-active' datapoint|dict_key:"id" %}>
                    {% if datapoint|dict_key:"is_active" %}
                    <span class="badge bg-success">Enabled</span>
                    {% else %}
                    <span class="badge bg-danger">Disabled</span>
                    {% endif %}
                    </a>
                </td>
                {% endwith %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
<div class="text-center pt-2">
    <a class="btn btn-outline-primary" href="{% url 'G1:G1-data-add' %}">Add Data</a>
</div>
<hr>
{% endblock %}

{% block breadcrumbs %}
<li class="breadcrumb-item">
    <a href="{% url 'my-experiments' %}">
        <span>My Experiments</span>
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'my-experiments-id' 'G1' %}">
        <span>G1</span>
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'G1:G1-data' %}">
        <span>Data Management</span>
    </a>
</li>
{% endblock %}